{
 "title": "Gitlab Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Gitlab", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gitlab E2E Latency < 10s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(probe_duration_seconds{job=\"gitlab_health_check\"}, \"path\", \"/$2\", \"instance\", \"(.*)onecmd.com(.*)\")",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "APP Instances between 1 ~ 30",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{service_port=\"9100\", ansible_role=\"gitlab_application_instance\"}) by (ansible_role)",
     "legendFormat": "{{ansible_role}}"
    }
   ]
  },
  {
   "title": "NFS Instances == 1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{service_port=\"9100\", ansible_role=\"nfs_host\"}) by (ansible_role)",
     "legendFormat": "{{ansible_role}}"
    }
   ]
  },
  {
   "title": "Gitlab APP instances(Scalling?)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{service_port=\"9100\", ansible_role=\"gitlab_application_instance\"}) by (ansible_role)",
     "legendFormat": "{{ansible_role}}"
    }
   ]
  },
  {
   "title": "Gitlab instances status ==1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"gitlab_node_exporters\"}",
     "legendFormat": "{{ansible_role}}:{{instance}}"
    }
   ]
  },
  {
   "title": "GitLab-Jenkins Build Trigger Time(< 1Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_merge_trigger_time", "legendFormat": "{{instance}}_Merge" },
    { "expr": "gitlab_push_trigger_time", "legendFormat": "{{instance}}_Push" }
   ]
  },
  {
   "title": "Gitlab Instances CPU Usage < 85%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance, ansible_role) (irate(node_cpu_seconds_total{job=\"gitlab_node_exporters\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ansible_role}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Gitlab Instances Memory Usage < 85%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_memory_MemAvailable_bytes{job=\"gitlab_node_exporters\"}*100/ node_memory_MemTotal_bytes{job=\"gitlab_node_exporters\"} ",
     "legendFormat": "{{ansible_role}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Gitlab Instances Disk Usage < 90%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (((node_filesystem_avail_bytes{job=\"gitlab_node_exporters\", fstype=~\"xfs|ext4\"}) * 100) / node_filesystem_size_bytes{job=\"gitlab_node_exporters\", fstype=~\"xfs|ext4\"})",
     "legendFormat": "{{ansible_role}}:{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "Gitlab Instances Disk Reads/Writes Completed < 6000",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"gitlab_node_exporters\", ansible_role=~\"gitlab_application_instance|nfs_host\"}[1m])",
     "legendFormat": "{{ansible_role}}:{{instance}}-{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"gitlab_node_exporters\", ansible_role=~\"gitlab_application_instance|nfs_host\"}[1m])",
     "legendFormat": "{{ansible_role}}:{{instance}}-{{device}} - Reads"
    }
   ]
  },
  {
   "title": "Total Projects|Users(If removed > 10 in 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gitlab_statistics{label!=\"merge_requests\", label=~\"projects|users\"}",
     "legendFormat": "Total {{label}}"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Gitlab metrics health & Prometheus status == 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"gitlab_node_exporters|gitlab_sidekiq_exporters|gitlab_gitaly_exporters|gitlab_health_check\"}",
     "legendFormat": "{{job}}:{{instance}}"
    }
   ]
  }
 ]
}