{
 "title": "Gitlab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Total Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gitlab_statistics{label=\"users\"}"
    }
   ]
  },
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gitlab_statistics{label=\"projects\"}"
    }
   ]
  },
  {
   "title": "Opened Merge Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gitlab_statistics{label=\"merge_requests_opened\"}"
    }
   ]
  },
  {
   "title": "Merged Merge Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "gitlab_statistics{label=\"merge_requests_merged\"}"
    }
   ]
  },
  {
   "title": "Total App Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{ansible_role=\"gitlab_application_instance\", service_port=\"9100\"}) by (ansible_role)"
    }
   ]
  },
  {
   "title": "Gitlab App",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status",
     "crit": 1,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "disabledValue": "1",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{job=\"gitlab_health_check\", instance=\"https://scm.onecmd.com/-/health\"}",
     "units": "short",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Gitlab Backend",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "probe_success",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "probe_success{job=\"gitlab_health_check\", instance=\"https://scm.onecmd.com/-/liveness\"}",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "NFS Server",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"gitlab_node_exporters\", ansible_role=\"nfs_host\"}"
    }
   ]
  },
  {
   "title": "App CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance_role) (irate(node_cpu_seconds_total{ansible_role=\"gitlab_application_instance\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "NFS Server CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{ansible_role=\"nfs_host\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Redis CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "CacheClusterId": "redis-server" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "region": "eu-central-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "db-server" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "eu-central-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "App Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance_role) (node_memory_MemAvailable_bytes{ansible_role=\"gitlab_application_instance\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"gitlab_application_instance\"} ))"
    }
   ]
  },
  {
   "title": "NFS Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance_role) (node_memory_MemAvailable_bytes{ansible_role=\"nfs_host\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"nfs_host\"} ))"
    }
   ]
  },
  {
   "title": "Redis Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "CacheClusterId": "redis-server" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "region": "eu-central-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NFS Git Repo Disk Usage",
   "type": "singlestat",
   "description": "Free use: \nThread: 1073741824,5073741824\nMax: 30023255552\nUsage use:\nThread: 2231943798780068,2331943798780068\nMax: 2431943798780068(2.16TB)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes-node_filesystem_avail_bytes{ ansible_role=\"nfs_host\", fstype=~\"xfs|ext4|rootfs\", device=\"/dev/nvme1n1\"}"
    }
   ]
  },
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Git Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (grpc_method,grpc_service,grpc_type) (\n  rate(grpc_server_started_total{cluster=\"$cluster\", grpc_service=~\"gitaly.*\"}[1m])\n)",
     "legendFormat": "{{instance}}-All"
    },
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"gitlab_gitaly_exporters\"}[1m]))",
     "legendFormat": "All-Total"
    }
   ]
  },
  {
   "title": "Gitlab Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gitlab_statistics{label!=\"merge_requests\"}",
     "legendFormat": "Total {{label}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance_role) (irate(node_cpu_seconds_total{ansible_role=\"gitlab_application_instance\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "APP"
    },
    {
     "expr": "100 - (avg by (instance_role) (irate(node_cpu_seconds_total{ansible_role=\"nfs_host\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "NFS"
    }
   ]
  },
  {
   "title": "Network Bytes Transmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{ansible_role=\"gitlab_application_instance\"}[1m]))",
     "legendFormat": "app-receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{ansible_role=\"gitlab_application_instance\"}[1m]))",
     "legendFormat": "app-sent"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{ansible_role=\"nfs_host\"}[1m]))",
     "legendFormat": "nfs-receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{ansible_role=\"nfs_host\"}[1m]))",
     "legendFormat": "nfs-sent"
    }
   ]
  },
  {
   "title": "Gitlab Total Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{service_port=\"9100\"}) by (ansible_role)",
     "legendFormat": "{{ansible_role}}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(probe_duration_seconds{job=\"gitlab_health_check\"}, \"path\", \"/$2\", \"instance\", \"(.*)onecmd.com(.*)\")",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "GitLab-Jenkins Build Trigger Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "gitlab_merge_trigger_time", "legendFormat": "{{instance}}_Merge" },
      { "expr": "gitlab_push_trigger_time", "legendFormat": "{{instance}}_Push" }
     ]
    },
    {
     "title": "Jenkins Total Time(Trigger Job+Start Pod + Build)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "gitlab_push_total_time", "legendFormat": "{{instance}}_Push" },
      { "expr": "gitlab_merge_total_time", "legendFormat": "{{instance}}_Merge" }
     ]
    }
   ]
  },
  {
   "title": "Gitlab App Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance_role) (node_memory_MemAvailable_bytes{ansible_role=\"gitlab_application_instance\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"gitlab_application_instance\"} ))",
       "legendFormat": "{{instance_role}}"
      }
     ]
    },
    {
     "title": "Git Requests(SSH* --> Git SSH, Post* --> Git HTTP)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_git_protocol_requests_total{}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",ansible_role=\"gitlab_application_instance\"}[1m])) * 100)",
       "legendFormat": "{{instance}}-total"
      }
     ]
    },
    {
     "title": "Git Service RatioGit Requests(SSH* --> Git SSH, SmartHttp* --> Git HTTP)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{ grpc_service=~\"gitaly.*\"}[1m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - node_memory_MemAvailable_bytes{ansible_role=\"gitlab_application_instance\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"gitlab_application_instance\"} ",
       "legendFormat": "{{instance}}-used"
      },
      {
       "expr": "node_memory_Buffers_bytes{ansible_role=\"gitlab_application_instance\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"gitlab_application_instance\"} ",
       "legendFormat": "{{instance}}-buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{ansible_role=\"gitlab_application_instance\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"gitlab_application_instance\"} ",
       "legendFormat": "{{instance}}-cached"
      }
     ]
    },
    {
     "title": "Git Requests(Git Requests(SSH* --> Git SSH, Post* --> Git HTTP)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_git_protocol_requests_total{}[1m])) by (instance, grpc_method)",
       "legendFormat": "{{instance}}-{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (((node_filesystem_avail_bytes{ansible_role=\"gitlab_application_instance\", fstype=~\"xfs|ext4|rootfs\"}) * 100) / node_filesystem_size_bytes{ansible_role=\"gitlab_application_instance\", fstype=~\"xfs|ext4|rootfs\"})",
       "legendFormat": "{{ansible_role}}-{{device}}"
      }
     ]
    },
    {
     "title": "Git Protocol Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_git_protocol_requests_total{}[1m])) by (instance)",
       "legendFormat": "{{instance}}-ALl"
      },
      {
       "expr": "sum(rate(gitaly_git_protocol_requests_total{}[1m]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Node Disk Available Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 53 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{ansible_role=\"gitlab_application_instance\", fstype=~\"ext4|xfs\"}",
       "legendFormat": "{{instance}}:{{device}}"
      }
     ]
    },
    {
     "title": "Sidekiq queue size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "topk(5, sidekiq_queue_size{})", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "CPU IOWait",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{ansible_role=\"gitlab_application_instance\",mode='iowait'}[1m]))*100 / sum by (instance)(irate(node_cpu_seconds_total{ansible_role=\"gitlab_application_instance\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{ansible_role=\"nfs_host\",mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - node_memory_MemAvailable_bytes{ansible_role=\"nfs_host\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"nfs_host\"} ",
       "legendFormat": "{{instance}}-used"
      },
      {
       "expr": "node_memory_Buffers_bytes{ansible_role=\"nfs_host\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"nfs_host\"} ",
       "legendFormat": "{{instance}}-buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{ansible_role=\"nfs_host\"}*100/ node_memory_MemTotal_bytes{ansible_role=\"nfs_host\"} ",
       "legendFormat": "{{instance}}-cached"
      }
     ]
    },
    {
     "title": "CPU IOWait %",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{ansible_role=\"nfs_host\",mode='iowait'}[1m]))*100 / sum by (instance)(irate(node_cpu_seconds_total{ansible_role=\"nfs_host\"}[1m]))",
       "legendFormat": "{{instance}}-iowait-%"
      }
     ]
    },
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{ansible_role=\"nfs_host\"}[1m])",
       "legendFormat": "{{instance}}-{{device}} - Reads"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{ansible_role=\"nfs_host\"}[1m])",
       "legendFormat": "{{instance}}-{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (((node_filesystem_avail_bytes{ ansible_role=\"nfs_host\", fstype=~\"xfs|ext4|rootfs\"}) * 100) / node_filesystem_size_bytes{ansible_role=\"nfs_host\", fstype=~\"xfs|ext4|rootfs\"})",
       "legendFormat": "{{instance}}: {{device}}"
      }
     ]
    },
    {
     "title": "Disk Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{ansible_role=\"nfs_host\", fstype=~\"xfs|ext4|rootfs\"}",
       "legendFormat": "{{instance}}:{{device}}"
      }
     ]
    },
    {
     "title": "NFS Git Repo Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes-node_filesystem_avail_bytes{job=\"gitlab_node_exporters\", ansible_role=\"nfs_host\", fstype=~\"xfs|ext4|rootfs\", device=\"/dev/nvme1n1\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk total files Inode used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{ansible_role=\"nfs_host\", device=\"/dev/nvme1n1\"} - node_filesystem_files_free{ansible_role=\"nfs_host\", device=\"/dev/nvme1n1\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis & DB Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "RDS",
       "dimensions": { "DBInstanceIdentifier": "db-server" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Redis",
       "dimensions": { "CacheClusterId": "redis-server" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Memory Free",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "RDS",
       "dimensions": { "DBInstanceIdentifier": "db-server" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Redis",
       "dimensions": { "CacheClusterId": "redis-server" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "RDS",
       "dimensions": { "DBInstanceIdentifier": "db-server" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "DB Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "db-server" },
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Write",
       "dimensions": { "DBInstanceIdentifier": "db-server" },
       "metricName": "WriteLatency",
       "namespace": "AWS/RDS",
       "region": "default",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Top Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "up{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{ansible_role}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Service Status And Down Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "alias": "Up",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "up{ansible_role=\"gitlab_application_instance\"}",
       "legendFormat": "{{instance}}",
       "units": "short",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Backup Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "gitlab_backup_status", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Gitaly connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(gitaly_connections_total[1m])",
       "legendFormat": "Gitaly connections"
      },
      {
       "expr": "sum(rate(grpc_client_handled_total{}[1m])) by (grpc_method) > 0",
       "legendFormat": "gprc-{{grpc_method}}"
      }
     ]
    },
    {
     "title": "NFSD Disk Read/Write",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_nfsd_disk_bytes_read_total{job=\"gitlab_node_exporters\"}[1m])",
       "legendFormat": "{{instance}}-read"
      },
      {
       "expr": "irate(node_nfsd_disk_bytes_written_total{job=\"gitlab_node_exporters\"}[1m])",
       "legendFormat": "{{instance}}-write"
      }
     ]
    },
    {
     "title": "Disk Read/Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{job=\"gitlab_node_exporters\"}[1m])",
       "legendFormat": "{{instance}}-{{device}}-write"
      },
      {
       "expr": "rate(node_disk_read_bytes_total{job=\"gitlab_node_exporters\"}[1m])",
       "legendFormat": "{{instance}}-{{device}}-read"
      }
     ]
    },
    {
     "title": "Node Disk IO Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{job=\"gitlab_node_exporters\",mode=\"iowait\"}[1m])) by (ansible_role, instance)",
       "legendFormat": "{{ansible_role}}: {{instance}}-iowait"
      },
      {
       "expr": "avg(irate(node_disk_read_time_seconds_total{job=\"gitlab_node_exporters\"}[1m])) by (ansible_role,instance)",
       "legendFormat": "{{ansible_role}}: {{instance}}-read"
      },
      {
       "expr": "avg(irate(node_disk_write_time_seconds_total{job=\"gitlab_node_exporters\"}[1m])) by (ansible_role,instance)",
       "legendFormat": "{{ansible_role}}: {{instance}}-write"
      }
     ]
    },
    {
     "title": "Network Bytes Transmit Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{job=\"gitlab_node_exporters\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-receive"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{job=\"gitlab_node_exporters\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-sent"
      }
     ]
    },
    {
     "title": "Network Package Transmit Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_packets_total{job=\"gitlab_node_exporters\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-receive"
      },
      {
       "expr": "sum(rate(node_network_transmit_packets_total{job=\"gitlab_node_exporters\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-sent"
      }
     ]
    },
    {
     "title": "CI Builds ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_stale_builds{}) by (instance)",
       "legendFormat": "{{instance}}-builds-stale"
      },
      {
       "expr": "sum(ci_created_builds{}) by (instance)",
       "legendFormat": "{{instance}}-builds-created"
      },
      {
       "expr": "sum(ci_pending_builds{}) by (instance)",
       "legendFormat": "{{instance}}-builds-pending"
      }
     ]
    },
    {
     "title": "Http Requests Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(promhttp_metric_handler_requests_total{job=\"gitlab_node_exporters\"}[1m])",
       "legendFormat": "{{instance}}-{{code}}"
      }
     ]
    },
    {
     "title": "sidekiq_queue_size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sidekiq_queue_size{}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Dead Jobs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sidekiq_dead_jobs{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "sidekiq_queue_latency_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(sidekiq_queue_latency_seconds{}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sidekiq_queue_paused",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(sidekiq_queue_paused{}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Gitaly Authentications Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(gitaly_authentications{}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_count{}) by (instance,name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitlab Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitaly Spawn Timeout Count ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "gitaly_spawn_timeout_count{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Gitlaly Connections Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(gitaly_connections_total{}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Go GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(go_gc_duration_seconds_sum{job=\"gitlab_gitaly_exporters\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Gitaly Client Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_service_client_requests{}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Grpc Server Handled Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(grpc_server_handled_total{}[1m])) by (instance, grpc_code)",
       "legendFormat": "{{instance}}-{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Gitaly Build Info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "gitlab_build_info{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "process_cpu_seconds ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(process_cpu_seconds_total{job=\"gitlab_sidekiq_exporters\"}[1m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Go Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{job=\"gitlab_gitaly_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes{job=\"gitlab_sidekiq_exporters\"}) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "GPRC Msg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(grpc_server_msg_received_total{}[1m])) by (instance)",
       "legendFormat": "{{instance}} Received"
      },
      {
       "expr": "sum(irate(grpc_server_msg_sent_total{}[1m])) by (instance)",
       "legendFormat": "{{instance}} Sent"
      }
     ]
    },
    {
     "title": "process_smaps_size_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "process_smaps_size_bytes{}", "legendFormat": "{{instance}}-{{name}}" }
     ]
    },
    {
     "title": "process_resident_memory_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{job=\"gitlab_sidekiq_exporters\"}) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Process Start Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(process_start_time_seconds{job=\"gitlab_sidekiq_exporters\"}[5m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Database Rows",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "gitlab_database_rows{}", "legendFormat": "{{instance}}-{{query_name}}" }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{job=\"gitlab_node_exporters\"}) by (cpu, instance)) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 74 },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total SWAP",
     "type": "table",
     "gridPos": { "h": 5, "w": 5, "x": 8, "y": 74 },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total RootFS",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 74 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"gitlab_node_exporters\", mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Uptime",
     "type": "table",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 74 },
     "targets": [
      {
       "expr": "node_time_seconds{job=\"gitlab_node_exporters\"} - node_boot_time_seconds{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load(1Min Avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load(5Min Avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_load5{job=\"gitlab_node_exporters\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}